### ISSUE TITLE
Not working on Magento 2.1.0RC1

### ISSUE THREAD

**Issue by quienti** [Sebwite/Magento2-Product-Downloads#3]
I do not have Tab in my products
Working fine on Magento 2.0.6 and lower

**Comment by JacobDrummond** [comment]
@sebwite,

Sebwite_ProductDownloads has stopped showing in product admin forms because currently adds its fieldset by extending Magento's [product tabs](/Sebwite/Magento2-Product-Downloads/blob/1.0.2/Block/Adminhtml/Product/Edit/Tabs.php#L17). 

However, in Magento 2.1, product form fieldsets are added via [form modifiers](/magento/magento2/blob/2.1.0/app/code/Magento/Catalog/Ui/DataProvider/Product/Form/Modifier/AbstractModifier.php).

For example, Magento_CatalogUrlRewrite adds its fieldset by:

1. Creating a concrete [form modifier](/magento/magento2/blob/2.1.0/app/code/Magento/CatalogUrlRewrite/Ui/DataProvider/Product/Form/Modifier/ProductUrlRewrite.php) that describes which fields need to be added.
2. [Registering the modifier](/magento/magento2/blob/2.1.0/app/code/Magento/CatalogUrlRewrite/etc/adminhtml/di.xml#L32) with Magento_Product's form modifier pool.

Could you implement the new form modifiers approach in Sebwite_ProductDownloads?

**Comment by JacobDrummond** [comment]
Product form documentation: http://devdocs.magento.com/guides/v2.1/howdoi/customize_product.html

**Comment by webdesk** [comment]
I'm still not able to see the download tab on the Magento 2.1.0

**Comment by vdharshan** [comment]
Having the same issue.. any ideas?

**Comment by tlygnersjo** [comment]
I'm also having the same issue on Magento 2.1.2. @sebwite

**Comment by sdelombaerde** [comment]
@sebwite
When can we expect a working solution for Magento 2.1.5?

**Comment by SilvanLaroo** [comment]
We've made the extension compatible with Magento 2.1, please check the 2.1 branch. We will release a stable version soon.
